In [22]:
#Import library yang dibutuhkan
import csv
import nltk
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [66]:
# Baca file excel
#, error_bad_lines=False
data_komentar = pd.read_excel('Data_Baru.xlsx')
data_komentar

                                                                                                                                                                                                                                                                                                                  text
0                                                                                                                                                                                        Yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa😢
1     Smoga Tuhan Jme Allah Swt mebrkahi bangsa dn Negara Indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa Indonesia kdpn mnjadi negra maju dn makmur  brkeadiln bg sluruh bangsa Indnedia .
2                                                                                                                                                                                                                        @dorra3175 iya gue tau lu lagi sakit mknya sdkit gendeng...pertnyaan gue tu emng gue knapa?..
3                                                                                                                                                                                                                                                                                                           Hidup PSI.
4                                                                                                                                                                                                                                                                                                             ❤️❤️❤️❤️
...                                                                                                                                                                                                                                                                                                                ...
4994                                                                                                                                                                             @octa_viandi apa yang mau di keluhin bang bukan nya skrg enak ya? Bahan pokok murah, hukum tidak bisa di otak atik, masyarakat makmur
4995                                                                                                                                                                     Itu pasti karena tujuannya Ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya
4996                                                                                                                                                                                                                                                                                        @jonaloftt Komentar Buzzer
4997                                                                                                                                                                                           @horaspangaribuan_ komentar terngakak. Emangnya ini negara pilih kasih?? Negara ini emang punya penguasa? Mikirr doong.
4998                                                                                                                                                                                                                                                                              Jgn bangga membangun dr uang hutang.

[4999 rows x 1 columns]

In [67]:
# Proses Cleaning Data dan Case Folding (Mengubah huruf menjadi kecil)
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemover, ArrayDictionary
import string
def remove_excessive_repetitions(text):
    # Mengganti lebih dari dua pengulangan karakter dengan dua karakter
    return re.sub(r'(.)\1{2,}', r'\1\1', text)
def filtering_text(text):
    # mengubah komentar menjadi huruf kecil
    text = text.lower()
    # menghilangkan url
    text = re.sub(r'https?:\/\/\S+','',text)
    # menghilangkan mention, link, hastag
    text = ' '.join(re.sub("([@@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", text).split())
    #menghilangkan karakter byte (b')
    text = re.sub(r'(b\'{1,2})',"", text)
    # menghilangkan yang bukan huruf
    text = re.sub('[^a-zA-Z]', ' ', text)
    # menghilangkan digit angka
    text = re.sub(r'\d+', '', text)
    #menghilangkan tanda baca
    text = text.translate(str.maketrans("","",string.punctuation))
    # menghilangkan whitespace berlebih
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [69]:
# Mengganti nilai NaN dengan string kosong dan memastikan semua nilai adalah string
data_komentar['text'] = data_komentar['text'].fillna('').astype(str)

In [70]:
# Mencetak hasil dari cleaning dan case folding data
data_komentar['Case Folding'] = data_komentar['text'].apply(filtering_text)
data_komentar

,text,Case Folding
0,Yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa😢,yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa
1,Smoga Tuhan Jme Allah Swt mebrkahi bangsa dn Negara Indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa Indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa Indnedia .,smoga tuhan jme allah swt mebrkahi bangsa dn negara indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa indnedia
2,@dorra3175 iya gue tau lu lagi sakit mknya sdkit gendeng...pertnyaan gue tu emng gue knapa?..,iya gue tau lu lagi sakit mknya sdkit gendeng pertnyaan gue tu emng gue knapa
3,Hidup PSI.,hidup psi
4,❤️❤️❤️❤️,
...,...,...
4994,"@octa_viandi apa yang mau di keluhin bang bukan nya skrg enak ya? Bahan pokok murah, hukum tidak bisa di otak atik, masyarakat makmur",viandi apa yang mau di keluhin bang bukan nya skrg enak ya bahan pokok murah hukum tidak bisa di otak atik masyarakat makmur
4995,Itu pasti karena tujuannya Ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,itu pasti karena tujuannya ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya
4996,@jonaloftt Komentar Buzzer,komentar buzzer
4997,@horaspangaribuan_ komentar terngakak. Emangnya ini negara pilih kasih?? Negara ini emang punya penguasa? Mikirr doong.,komentar terngakak emangnya ini negara pilih kasih negara ini emang punya penguasa mikirr doong
4998,Jgn bangga membangun dr uang hutang.,jgn bangga membangun dr uang hutang

In [71]:
# Melakukan Tokenizing terhadap data
def word_tokenize_wrapper(text):
    return word_tokenize(text)



data_komentar['Tokenizing'] = data_komentar['Case Folding'].apply(word_tokenize_wrapper)
data_komentar

,text,Case Folding,Tokenizing
0,Yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa😢,yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa,"[yallah, segitunya, beliau, menataaa, nya, dengan, tanggung, jawab, padahal, ia, tauu, tahun, depan, bukan, lagi, ia, yang, akan, menempatinyaa]"
1,Smoga Tuhan Jme Allah Swt mebrkahi bangsa dn Negara Indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa Indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa Indnedia .,smoga tuhan jme allah swt mebrkahi bangsa dn negara indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa indnedia,"[smoga, tuhan, jme, allah, swt, mebrkahi, bangsa, dn, negara, indonesia, maju, sklipn, banjak, halngan, dn, ganguan, baik, dr, dalam, mau, dr, luar, bukan, mnjdi, suatu, halngan, besar, sbliknja, mnjadi, slh, satu, smangat, dn, motipasi, untk, mebngun, bangsa, indonesia, kdpn, mnjadi, negra, maju, dn, makmur, brkeadiln, bg, sluruh, bangsa, indnedia]"
2,@dorra3175 iya gue tau lu lagi sakit mknya sdkit gendeng...pertnyaan gue tu emng gue knapa?..,iya gue tau lu lagi sakit mknya sdkit gendeng pertnyaan gue tu emng gue knapa,"[iya, gue, tau, lu, lagi, sakit, mknya, sdkit, gendeng, pertnyaan, gue, tu, emng, gue, knapa]"
3,Hidup PSI.,hidup psi,"[hidup, psi]"
4,❤️❤️❤️❤️,,[]
...,...,...,...
4994,"@octa_viandi apa yang mau di keluhin bang bukan nya skrg enak ya? Bahan pokok murah, hukum tidak bisa di otak atik, masyarakat makmur",viandi apa yang mau di keluhin bang bukan nya skrg enak ya bahan pokok murah hukum tidak bisa di otak atik masyarakat makmur,"[viandi, apa, yang, mau, di, keluhin, bang, bukan, nya, skrg, enak, ya, bahan, pokok, murah, hukum, tidak, bisa, di, otak, atik, masyarakat, makmur]"
4995,Itu pasti karena tujuannya Ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,itu pasti karena tujuannya ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,"[itu, pasti, karena, tujuannya, ikam, ini, untuk, membuat, peluang, pekerjaan, mungkin, dong, biar, nasi, juga, bisa, lari, karena, banyak, orang, pekerja, bisanya]"
4996,@jonaloftt Komentar Buzzer,komentar buzzer,"[komentar, buzzer]"
4997,@horaspangaribuan_ komentar terngakak. Emangnya ini negara pilih kasih?? Negara ini emang punya penguasa? Mikirr doong.,komentar terngakak emangnya ini negara pilih kasih negara ini emang punya penguasa mikirr doong,"[komentar, terngakak, emangnya, ini, negara, pilih, kasih, negara, ini, emang, punya, penguasa, mikirr, doong]"
4998,Jgn bangga membangun dr uang hutang.,jgn bangga membangun dr uang hutang,"[jgn, bangga, membangun, dr, uang, hutang]"

In [72]:
# Melakukan Word Handling (Normalisasi)
# Kamus Slangs yang digunakan merupakan kamus yang diambil dari situs github 
# https://github.com/adeariniputri/text-preprocesing

kamus_normalisasi = pd.read_csv("slang.csv")

kata_normalisasi_dict = {}

for index, row in kamus_normalisasi.iterrows():
    if row[0] not in kata_normalisasi_dict:
        kata_normalisasi_dict[row[0]] = row[1] 
        
def normalisasi_kata(document):
    return [kata_normalisasi_dict[term] if term in kata_normalisasi_dict else term for term in document]

data_komentar['Word Handling'] = data_komentar['Tokenizing'].apply(normalisasi_kata)
data_komentar

,text,Case Folding,Tokenizing,Word Handling
0,Yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa😢,yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa,"[yallah, segitunya, beliau, menataaa, nya, dengan, tanggung, jawab, padahal, ia, tauu, tahun, depan, bukan, lagi, ia, yang, akan, menempatinyaa]","[yallah, segitunya, beliau, menataaa, nya, dengan, tanggung, jawab, padahal, ia, tahu, tahun, depan, bukan, lagi, ia, yang, akan, menempatinyaa]"
1,Smoga Tuhan Jme Allah Swt mebrkahi bangsa dn Negara Indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa Indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa Indnedia .,smoga tuhan jme allah swt mebrkahi bangsa dn negara indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa indnedia,"[smoga, tuhan, jme, allah, swt, mebrkahi, bangsa, dn, negara, indonesia, maju, sklipn, banjak, halngan, dn, ganguan, baik, dr, dalam, mau, dr, luar, bukan, mnjdi, suatu, halngan, besar, sbliknja, mnjadi, slh, satu, smangat, dn, motipasi, untk, mebngun, bangsa, indonesia, kdpn, mnjadi, negra, maju, dn, makmur, brkeadiln, bg, sluruh, bangsa, indnedia]","[smoga, tuhan, jme, allah, swt, mebrkahi, bangsa, dan, negara, indonesia, maju, sklipn, banjak, halngan, dan, ganguan, baik, dari, dalam, mau, dari, luar, bukan, mnjdi, suatu, halngan, besar, sbliknja, mnjadi, slh, satu, smangat, dan, motipasi, untk, mebngun, bangsa, indonesia, kdpn, mnjadi, negra, maju, dan, makmur, brkeadiln, bg, sluruh, bangsa, indnedia]"
2,@dorra3175 iya gue tau lu lagi sakit mknya sdkit gendeng...pertnyaan gue tu emng gue knapa?..,iya gue tau lu lagi sakit mknya sdkit gendeng pertnyaan gue tu emng gue knapa,"[iya, gue, tau, lu, lagi, sakit, mknya, sdkit, gendeng, pertnyaan, gue, tu, emng, gue, knapa]","[iya, aku, tau, lu, lagi, sakit, mknya, sdkit, gendeng, pertnyaan, aku, itu, memang, aku, knapa]"
3,Hidup PSI.,hidup psi,"[hidup, psi]","[hidup, psi]"
4,❤️❤️❤️❤️,,[],[]
...,...,...,...,...
4994,"@octa_viandi apa yang mau di keluhin bang bukan nya skrg enak ya? Bahan pokok murah, hukum tidak bisa di otak atik, masyarakat makmur",viandi apa yang mau di keluhin bang bukan nya skrg enak ya bahan pokok murah hukum tidak bisa di otak atik masyarakat makmur,"[viandi, apa, yang, mau, di, keluhin, bang, bukan, nya, skrg, enak, ya, bahan, pokok, murah, hukum, tidak, bisa, di, otak, atik, masyarakat, makmur]","[viandi, apa, yang, mau, di, keluhin, kakak, bukan, nya, sekarang, enak, ya, bahan, pokok, murah, hukum, tidak, bisa, di, otak, atik, masyarakat, makmur]"
4995,Itu pasti karena tujuannya Ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,itu pasti karena tujuannya ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,"[itu, pasti, karena, tujuannya, ikam, ini, untuk, membuat, peluang, pekerjaan, mungkin, dong, biar, nasi, juga, bisa, lari, karena, banyak, orang, pekerja, bisanya]","[itu, pasti, karena, tujuannya, ikam, ini, untuk, membuat, peluang, pekerjaan, mungkin, dong, biar, nasi, juga, bisa, lari, karena, banyak, orang, pekerja, bisanya]"
4996,@jonaloftt Komentar Buzzer,komentar buzzer,"[komentar, buzzer]","[komentar, buzzer]"
4997,@horaspangaribuan_ komentar terngakak. Emangnya ini negara pilih kasih?? Negara ini emang punya penguasa? Mikirr doong.,komentar terngakak emangnya ini negara pilih kasih negara ini emang punya penguasa mikirr doong,"[komentar, terngakak, emangnya, ini, negara, pilih, kasih, negara, ini, emang, punya, penguasa, mikirr, doong]","[komentar, terngakak, emangnya, ini, negara, pilih, kasih, negara, ini, memang, punya, penguasa, mikirr, doong]"
4998,Jgn bangga membangun dr uang hutang.,jgn bangga membangun dr uang hutang,"[jgn, bangga, membangun, dr, uang, hutang]","[jangan, bangga, membangun, dari, uang, hutang]"

In [73]:
# Mengimport stopwords
# nltk.download('stopwords')
from nltk.corpus import stopwords

# Membuat agar variabel list_stopwords berisi stopwords berbahasa indonesia
list_stopwords = stopwords.words('indonesian')

# Membuat kamus stopwords 
list_stopwords = set(list_stopwords)

# Melakukan stopwords pada kata
def stopwords_removal(tokenized_text):
    return [word for word in tokenized_text if word not in list_stopwords]

data_komentar['Filtering'] = data_komentar['Word Handling'].apply(stopwords_removal)
data_komentar = data_komentar.astype(str)
data_komentar

,text,Case Folding,Tokenizing,Word Handling,Filtering
0,Yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa😢,yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa,"['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'dengan', 'tanggung', 'jawab', 'padahal', 'ia', 'tauu', 'tahun', 'depan', 'bukan', 'lagi', 'ia', 'yang', 'akan', 'menempatinyaa']","['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'dengan', 'tanggung', 'jawab', 'padahal', 'ia', 'tahu', 'tahun', 'depan', 'bukan', 'lagi', 'ia', 'yang', 'akan', 'menempatinyaa']","['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'tanggung', 'menempatinyaa']"
1,Smoga Tuhan Jme Allah Swt mebrkahi bangsa dn Negara Indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa Indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa Indnedia .,smoga tuhan jme allah swt mebrkahi bangsa dn negara indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa indnedia,"['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'dn', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'dn', 'ganguan', 'baik', 'dr', 'dalam', 'mau', 'dr', 'luar', 'bukan', 'mnjdi', 'suatu', 'halngan', 'besar', 'sbliknja', 'mnjadi', 'slh', 'satu', 'smangat', 'dn', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'dn', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']","['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'dan', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'dan', 'ganguan', 'baik', 'dari', 'dalam', 'mau', 'dari', 'luar', 'bukan', 'mnjdi', 'suatu', 'halngan', 'besar', 'sbliknja', 'mnjadi', 'slh', 'satu', 'smangat', 'dan', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'dan', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']","['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'ganguan', 'mnjdi', 'halngan', 'sbliknja', 'mnjadi', 'slh', 'smangat', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']"
2,@dorra3175 iya gue tau lu lagi sakit mknya sdkit gendeng...pertnyaan gue tu emng gue knapa?..,iya gue tau lu lagi sakit mknya sdkit gendeng pertnyaan gue tu emng gue knapa,"['iya', 'gue', 'tau', 'lu', 'lagi', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'gue', 'tu', 'emng', 'gue', 'knapa']","['iya', 'aku', 'tau', 'lu', 'lagi', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'aku', 'itu', 'memang', 'aku', 'knapa']","['iya', 'tau', 'lu', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'knapa']"
3,Hidup PSI.,hidup psi,"['hidup', 'psi']","['hidup', 'psi']","['hidup', 'psi']"
4,❤️❤️❤️❤️,,[],[],[]
...,...,...,...,...,...
4994,"@octa_viandi apa yang mau di keluhin bang bukan nya skrg enak ya? Bahan pokok murah, hukum tidak bisa di otak atik, masyarakat makmur",viandi apa yang mau di keluhin bang bukan nya skrg enak ya bahan pokok murah hukum tidak bisa di otak atik masyarakat makmur,"['viandi', 'apa', 'yang', 'mau', 'di', 'keluhin', 'bang', 'bukan', 'nya', 'skrg', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'tidak', 'bisa', 'di', 'otak', 'atik', 'masyarakat', 'makmur']","['viandi', 'apa', 'yang', 'mau', 'di', 'keluhin', 'kakak', 'bukan', 'nya', 'sekarang', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'tidak', 'bisa', 'di', 'otak', 'atik', 'masyarakat', 'makmur']","['viandi', 'keluhin', 'kakak', 'nya', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'otak', 'atik', 'masyarakat', 'makmur']"
4995,Itu pasti karena tujuannya Ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,itu pasti karena tujuannya ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,"['itu', 'pasti', 'karena', 'tujuannya', 'ikam', 'ini', 'untuk', 'membuat', 'peluang', 'pekerjaan', 'mungkin', 'dong', 'biar', 'nasi', 'juga', 'bisa', 'lari', 'karena', 'banyak', 'orang', 'pekerja', 'bisanya']","['itu', 'pasti', 'karena', 'tujuannya', 'ikam', 'ini', 'untuk', 'membuat', 'peluang', 'pekerjaan', 'mungkin', 'dong', 'biar', 'nasi', 'juga', 'bisa', 'lari', 'karena', 'banyak', 'orang', 'pekerja', 'bisanya']","['tujuannya', 'ikam', 'peluang', 'pekerjaan', 'biar', 'nasi', 'lari', 'orang', 'pekerja', 'bisanya']"
4996,@jonaloftt Komentar Buzzer,komentar buzzer,"['komentar', 'buzzer']","['komentar', 'buzzer']","['komentar', 'buzzer']"
4997,@horaspangaribuan_ komentar terngakak. Emangnya ini negara pilih kasih?? Negara ini emang punya penguasa? Mikirr doong.,komentar terngakak emangnya ini negara pilih kasih negara ini emang punya penguasa mikirr doong,"['komentar', 'terngakak', 'emangnya', 'ini', 'negara', 'pilih', 'kasih', 'negara', 'ini', 'emang', 'punya', 'penguasa', 'mikirr', 'doong']","['komentar', 'terngakak', 'emangnya', 'ini', 'negara', 'pilih', 'kasih', 'negara', 'ini', 'memang', 'punya', 'penguasa', 'mikirr', 'doong']","['komentar', 'terngakak', 'emangnya', 'negara', 'pilih', 'kasih', 'negara', 'penguasa', 'mikirr', 'doong']"
4998,Jgn bangga membangun dr uang hutang.,jgn bangga membangun dr uang hutang,"['jgn', 'bangga', 'membangun', 'dr', 'uang', 'hutang']","['jangan', 'bangga', 'membangun', 'dari', 'uang', 'hutang']","['bangga', 'membangun', 'uang', 'hutang']"

In [74]:
# Proses Stemming
def stemming(tokenized_text):
    # stemming
    factory_stemmer = StemmerFactory()
    stemmer = factory_stemmer.create_stemmer()
    text = stemmer.stem(tokenized_text)
    return text

data_komentar['Stemming'] = data_komentar['Filtering'].apply(stemming)
data_komentar = data_komentar.astype(str)
data_komentar

,text,Case Folding,Tokenizing,Word Handling,Filtering,Stemming
0,Yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa😢,yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa,"['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'dengan', 'tanggung', 'jawab', 'padahal', 'ia', 'tauu', 'tahun', 'depan', 'bukan', 'lagi', 'ia', 'yang', 'akan', 'menempatinyaa']","['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'dengan', 'tanggung', 'jawab', 'padahal', 'ia', 'tahu', 'tahun', 'depan', 'bukan', 'lagi', 'ia', 'yang', 'akan', 'menempatinyaa']","['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'tanggung', 'menempatinyaa']",yallah segitunya beliau menataaa nya tanggung menempatinyaa
1,Smoga Tuhan Jme Allah Swt mebrkahi bangsa dn Negara Indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa Indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa Indnedia .,smoga tuhan jme allah swt mebrkahi bangsa dn negara indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa indnedia,"['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'dn', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'dn', 'ganguan', 'baik', 'dr', 'dalam', 'mau', 'dr', 'luar', 'bukan', 'mnjdi', 'suatu', 'halngan', 'besar', 'sbliknja', 'mnjadi', 'slh', 'satu', 'smangat', 'dn', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'dn', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']","['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'dan', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'dan', 'ganguan', 'baik', 'dari', 'dalam', 'mau', 'dari', 'luar', 'bukan', 'mnjdi', 'suatu', 'halngan', 'besar', 'sbliknja', 'mnjadi', 'slh', 'satu', 'smangat', 'dan', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'dan', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']","['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'ganguan', 'mnjdi', 'halngan', 'sbliknja', 'mnjadi', 'slh', 'smangat', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']",smoga tuhan jme allah swt mebrkahi bangsa negara indonesia maju sklipn banjak halngan ganguan mnjdi halngan sbliknja mnjadi slh smangat motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju makmur brkeadiln bg sluruh bangsa indnedia
2,@dorra3175 iya gue tau lu lagi sakit mknya sdkit gendeng...pertnyaan gue tu emng gue knapa?..,iya gue tau lu lagi sakit mknya sdkit gendeng pertnyaan gue tu emng gue knapa,"['iya', 'gue', 'tau', 'lu', 'lagi', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'gue', 'tu', 'emng', 'gue', 'knapa']","['iya', 'aku', 'tau', 'lu', 'lagi', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'aku', 'itu', 'memang', 'aku', 'knapa']","['iya', 'tau', 'lu', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'knapa']",iya tau lu sakit mknya sdkit gendeng pertnyaan knapa
3,Hidup PSI.,hidup psi,"['hidup', 'psi']","['hidup', 'psi']","['hidup', 'psi']",hidup psi
4,❤️❤️❤️❤️,,[],[],[],
...,...,...,...,...,...,...
4994,"@octa_viandi apa yang mau di keluhin bang bukan nya skrg enak ya? Bahan pokok murah, hukum tidak bisa di otak atik, masyarakat makmur",viandi apa yang mau di keluhin bang bukan nya skrg enak ya bahan pokok murah hukum tidak bisa di otak atik masyarakat makmur,"['viandi', 'apa', 'yang', 'mau', 'di', 'keluhin', 'bang', 'bukan', 'nya', 'skrg', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'tidak', 'bisa', 'di', 'otak', 'atik', 'masyarakat', 'makmur']","['viandi', 'apa', 'yang', 'mau', 'di', 'keluhin', 'kakak', 'bukan', 'nya', 'sekarang', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'tidak', 'bisa', 'di', 'otak', 'atik', 'masyarakat', 'makmur']","['viandi', 'keluhin', 'kakak', 'nya', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'otak', 'atik', 'masyarakat', 'makmur']",viandi keluhin kakak nya enak ya bahan pokok murah hukum otak atik masyarakat makmur
4995,Itu pasti karena tujuannya Ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,itu pasti karena tujuannya ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,"['itu', 'pasti', 'karena', 'tujuannya', 'ikam', 'ini', 'untuk', 'membuat', 'peluang', 'pekerjaan', 'mungkin', 'dong', 'biar', 'nasi', 'juga', 'bisa', 'lari', 'karena', 'banyak', 'orang', 'pekerja', 'bisanya']","['itu', 'pasti', 'karena', 'tujuannya', 'ikam', 'ini', 'untuk', 'membuat', 'peluang', 'pekerjaan', 'mungkin', 'dong', 'biar', 'nasi', 'juga', 'bisa', 'lari', 'karena', 'banyak', 'orang', 'pekerja', 'bisanya']","['tujuannya', 'ikam', 'peluang', 'pekerjaan', 'biar', 'nasi', 'lari', 'orang', 'pekerja', 'bisanya']",tuju ikam peluang kerja biar nasi lari orang kerja bisa
4996,@jonaloftt Komentar Buzzer,komentar buzzer,"['komentar', 'buzzer']","['komentar', 'buzzer']","['komentar', 'buzzer']",komentar buzzer
4997,@horaspangaribuan_ komentar terngakak. Emangnya ini negara pilih kasih?? Negara ini emang punya penguasa? Mikirr doong.,komentar terngakak emangnya ini negara pilih kasih negara ini emang punya penguasa mikirr doong,"['komentar', 'terngakak', 'emangnya', 'ini', 'negara', 'pilih', 'kasih', 'negara', 'ini', 'emang', 'punya', 'penguasa', 'mikirr', 'doong']","['komentar', 'terngakak', 'emangnya', 'ini', 'negara', 'pilih', 'kasih', 'negara', 'ini', 'memang', 'punya', 'penguasa', 'mikirr', 'doong']","['komentar', 'terngakak', 'emangnya', 'negara', 'pilih', 'kasih', 'negara', 'penguasa', 'mikirr', 'doong']",komentar terngakak emang negara pilih kasih negara kuasa mikirr doong
4998,Jgn bangga membangun dr uang hutang.,jgn bangga membangun dr uang hutang,"['jgn', 'bangga', 'membangun', 'dr', 'uang', 'hutang']","['jangan', 'bangga', 'membangun', 'dari', 'uang', 'hutang']","['bangga', 'membangun', 'uang', 'hutang']",bangga bangun uang hutang

In [75]:
data_komentar['Data Clean'] = data_komentar['Stemming']
data_komentar

,text,Case Folding,Tokenizing,Word Handling,Filtering,Stemming,Data Clean
0,Yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa😢,yallah segitunya beliau menataaa nya dengan tanggung jawab padahal ia tauu tahun depan bukan lagi ia yang akan menempatinyaa,"['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'dengan', 'tanggung', 'jawab', 'padahal', 'ia', 'tauu', 'tahun', 'depan', 'bukan', 'lagi', 'ia', 'yang', 'akan', 'menempatinyaa']","['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'dengan', 'tanggung', 'jawab', 'padahal', 'ia', 'tahu', 'tahun', 'depan', 'bukan', 'lagi', 'ia', 'yang', 'akan', 'menempatinyaa']","['yallah', 'segitunya', 'beliau', 'menataaa', 'nya', 'tanggung', 'menempatinyaa']",yallah segitunya beliau menataaa nya tanggung menempatinyaa,yallah segitunya beliau menataaa nya tanggung menempatinyaa
1,Smoga Tuhan Jme Allah Swt mebrkahi bangsa dn Negara Indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa Indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa Indnedia .,smoga tuhan jme allah swt mebrkahi bangsa dn negara indonesia maju sklipn banjak halngan dn ganguan baik dr dalam mau dr luar bukan mnjdi suatu halngan besar sbliknja mnjadi slh satu smangat dn motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju dn makmur brkeadiln bg sluruh bangsa indnedia,"['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'dn', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'dn', 'ganguan', 'baik', 'dr', 'dalam', 'mau', 'dr', 'luar', 'bukan', 'mnjdi', 'suatu', 'halngan', 'besar', 'sbliknja', 'mnjadi', 'slh', 'satu', 'smangat', 'dn', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'dn', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']","['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'dan', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'dan', 'ganguan', 'baik', 'dari', 'dalam', 'mau', 'dari', 'luar', 'bukan', 'mnjdi', 'suatu', 'halngan', 'besar', 'sbliknja', 'mnjadi', 'slh', 'satu', 'smangat', 'dan', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'dan', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']","['smoga', 'tuhan', 'jme', 'allah', 'swt', 'mebrkahi', 'bangsa', 'negara', 'indonesia', 'maju', 'sklipn', 'banjak', 'halngan', 'ganguan', 'mnjdi', 'halngan', 'sbliknja', 'mnjadi', 'slh', 'smangat', 'motipasi', 'untk', 'mebngun', 'bangsa', 'indonesia', 'kdpn', 'mnjadi', 'negra', 'maju', 'makmur', 'brkeadiln', 'bg', 'sluruh', 'bangsa', 'indnedia']",smoga tuhan jme allah swt mebrkahi bangsa negara indonesia maju sklipn banjak halngan ganguan mnjdi halngan sbliknja mnjadi slh smangat motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju makmur brkeadiln bg sluruh bangsa indnedia,smoga tuhan jme allah swt mebrkahi bangsa negara indonesia maju sklipn banjak halngan ganguan mnjdi halngan sbliknja mnjadi slh smangat motipasi untk mebngun bangsa indonesia kdpn mnjadi negra maju makmur brkeadiln bg sluruh bangsa indnedia
2,@dorra3175 iya gue tau lu lagi sakit mknya sdkit gendeng...pertnyaan gue tu emng gue knapa?..,iya gue tau lu lagi sakit mknya sdkit gendeng pertnyaan gue tu emng gue knapa,"['iya', 'gue', 'tau', 'lu', 'lagi', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'gue', 'tu', 'emng', 'gue', 'knapa']","['iya', 'aku', 'tau', 'lu', 'lagi', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'aku', 'itu', 'memang', 'aku', 'knapa']","['iya', 'tau', 'lu', 'sakit', 'mknya', 'sdkit', 'gendeng', 'pertnyaan', 'knapa']",iya tau lu sakit mknya sdkit gendeng pertnyaan knapa,iya tau lu sakit mknya sdkit gendeng pertnyaan knapa
3,Hidup PSI.,hidup psi,"['hidup', 'psi']","['hidup', 'psi']","['hidup', 'psi']",hidup psi,hidup psi
4,❤️❤️❤️❤️,,[],[],[],,
...,...,...,...,...,...,...,...
4994,"@octa_viandi apa yang mau di keluhin bang bukan nya skrg enak ya? Bahan pokok murah, hukum tidak bisa di otak atik, masyarakat makmur",viandi apa yang mau di keluhin bang bukan nya skrg enak ya bahan pokok murah hukum tidak bisa di otak atik masyarakat makmur,"['viandi', 'apa', 'yang', 'mau', 'di', 'keluhin', 'bang', 'bukan', 'nya', 'skrg', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'tidak', 'bisa', 'di', 'otak', 'atik', 'masyarakat', 'makmur']","['viandi', 'apa', 'yang', 'mau', 'di', 'keluhin', 'kakak', 'bukan', 'nya', 'sekarang', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'tidak', 'bisa', 'di', 'otak', 'atik', 'masyarakat', 'makmur']","['viandi', 'keluhin', 'kakak', 'nya', 'enak', 'ya', 'bahan', 'pokok', 'murah', 'hukum', 'otak', 'atik', 'masyarakat', 'makmur']",viandi keluhin kakak nya enak ya bahan pokok murah hukum otak atik masyarakat makmur,viandi keluhin kakak nya enak ya bahan pokok murah hukum otak atik masyarakat makmur
4995,Itu pasti karena tujuannya Ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,itu pasti karena tujuannya ikam ini untuk membuat peluang pekerjaan mungkin dong biar nasi juga bisa lari karena banyak orang pekerja bisanya,"['itu', 'pasti', 'karena', 'tujuannya', 'ikam', 'ini', 'untuk', 'membuat', 'peluang', 'pekerjaan', 'mungkin', 'dong', 'biar', 'nasi', 'juga', 'bisa', 'lari', 'karena', 'banyak', 'orang', 'pekerja', 'bisanya']","['itu', 'pasti', 'karena', 'tujuannya', 'ikam', 'ini', 'untuk', 'membuat', 'peluang', 'pekerjaan', 'mungkin', 'dong', 'biar', 'nasi', 'juga', 'bisa', 'lari', 'karena', 'banyak', 'orang', 'pekerja', 'bisanya']","['tujuannya', 'ikam', 'peluang', 'pekerjaan', 'biar', 'nasi', 'lari', 'orang', 'pekerja', 'bisanya']",tuju ikam peluang kerja biar nasi lari orang kerja bisa,tuju ikam peluang kerja biar nasi lari orang kerja bisa
4996,@jonaloftt Komentar Buzzer,komentar buzzer,"['komentar', 'buzzer']","['komentar', 'buzzer']","['komentar', 'buzzer']",komentar buzzer,komentar buzzer
4997,@horaspangaribuan_ komentar terngakak. Emangnya ini negara pilih kasih?? Negara ini emang punya penguasa? Mikirr doong.,komentar terngakak emangnya ini negara pilih kasih negara ini emang punya penguasa mikirr doong,"['komentar', 'terngakak', 'emangnya', 'ini', 'negara', 'pilih', 'kasih', 'negara', 'ini', 'emang', 'punya', 'penguasa', 'mikirr', 'doong']","['komentar', 'terngakak', 'emangnya', 'ini', 'negara', 'pilih', 'kasih', 'negara', 'ini', 'memang', 'punya', 'penguasa', 'mikirr', 'doong']","['komentar', 'terngakak', 'emangnya', 'negara', 'pilih', 'kasih', 'negara', 'penguasa', 'mikirr', 'doong']",komentar terngakak emang negara pilih kasih negara kuasa mikirr doong,komentar terngakak emang negara pilih kasih negara kuasa mikirr doong
4998,Jgn bangga membangun dr uang hutang.,jgn bangga membangun dr uang hutang,"['jgn', 'bangga', 'membangun', 'dr', 'uang', 'hutang']","['jangan', 'bangga', 'membangun', 'dari', 'uang', 'hutang']","['bangga', 'membangun', 'uang', 'hutang']",bangga bangun uang hutang,bangga bangun uang hutang

In [82]:
# Menyimpan data ke dalam file CSV dengan nama kolom sebagai header
data_komentar['Data Clean'].to_csv('data_clean.csv', index=False)